### ISSUE TITLE
Work on conformance with twitter-text-conformance

### ISSUE THREAD

**Issue by edmondburnett** [edmondburnett/twitter-text-python#5]
See ianozsvald/twitter-text-python#5

https://github.com/twitter/twitter-text-conformance

**Comment by pykler** [comment]
+1 this needs to conform, otherwise should not be called twitter-text-python

**Comment by melinath** [comment]
Conformance tests are now _actually_ at https://github.com/twitter/twitter-text. Just ran into this as well, re: protocol-less links.
